Repository asfadmin/archive_heatmaps, pull requests merged in 2024-06, with the labels that each got.

#14 Implemented Quad Tree
  heatmap.py
  quad_poly.py
Labels: enhancement

#15 Merge Similar Satellite Images
  README.md
  heatmap.py
  quad_poly.py
Labels: documentation, enhancement

#19 Renamed heatmap.py to ingest.py
  data-ingest/ingest.py
Labels: documentation

#24 Export Optimizations
  README.md
  data-ingest/Docker/Dockerfile
  data-ingest/Docker/env.yml
  data-ingest/Docker/run.sh
  data-ingest/Dockerfile
  data-ingest/Resources/world-boundaries.cpg
  data-ingest/Resources/world-boundaries.dbf
  data-ingest/Resources/world-boundaries.prj
  data-ingest/Resources/world-boundaries.shp
  data-ingest/Resources/world-boundaries.shx
  data-ingest/create_sql.py
  data-ingest/data_merger.py
  data-ingest/ingest.py
  data-ingest/quad_tree.py
Labels: enhancement, optimization

#25 Add Webservice!
  Cargo.toml
  data-ingest/Dockerfile
  data-ingest/Resources/world-boundaries.cpg
  data-ingest/Resources/world-boundaries.dbf
  data-ingest/Resources/world-boundaries.prj
  data-ingest/Resources/world-boundaries.shp
  data-ingest/Resources/world-boundaries.shx
  data-ingest/create_sql.py
  data-ingest/heatmap.py
  data-ingest/quad_poly.py
  heatmap-service/.dockerignore
  heatmap-service/Cargo.lock
  heatmap-service/Cargo.toml
  heatmap-service/Dockerfile
  heatmap-service/README.md
  heatmap-service/sql/end_date.sql
  heatmap-service/sql/fetch_dataset.sql
  heatmap-service/sql/start_date.sql
  heatmap-service/src/config.rs
  heatmap-service/src/dataset.rs
  heatmap-service/src/error.rs
  heatmap-service/src/geo_json_path.rs
  heatmap-service/src/granule.rs
  heatmap-service/src/heatmap_data.rs
  heatmap-service/src/heatmap_response.rs
  heatmap-service/src/main.rs
  heatmap-service/src/middleware.rs
  heatmap-service/src/query.rs
  heatmap-service/src/redis.rs
  heatmap-service/src/tests/add_granule.sql
  heatmap-service/src/tests/mod.rs
  heatmap-service/src/tests/testing_cleanup.sql
  heatmap-service/src/tests/testing_init.sql
Labels: enhancement

#26 Leptos wgpu component
  .cargo/config.toml
  .gitignore
  Cargo.lock
  Cargo.toml
  data-ingest/Resources/world-boundaries.cpg
  data-ingest/Resources/world-boundaries.dbf
  data-ingest/Resources/world-boundaries.prj
  data-ingest/Resources/world-boundaries.shp
  data-ingest/Resources/world-boundaries.shx
  heatmap-client/.cargo/config.toml
  heatmap-client/Cargo.toml
  heatmap-client/index.html
  heatmap-client/rust-toolchain.toml
  heatmap-client/rustfmt.toml
  heatmap-client/src/heatmap/app.rs
  heatmap-client/src/heatmap/canvas.rs
  heatmap-client/src/heatmap/geometry.rs
  heatmap-client/src/heatmap/mod.rs
  heatmap-client/src/heatmap/render_context.rs
  heatmap-client/src/heatmap/shaders/shader.wgsl
  heatmap-client/src/heatmap/state.rs
  heatmap-client/src/main.rs
  heatmap-service/src/main.rs
  heatmap-service/src/query.rs
  rust-toolchain.toml
  rustfmt.toml
Labels: enhancement
